### ISSUE TITLE
Same flags is getting displayed for multiple countries.

### ISSUE THREAD

**Issue by tavinashb** [bl00mber/react-phone-input-2#246] opened 2020-06-08 12:51 UTC
I am trying to implement styling as same as https://bl00mber.github.io/react-phone-input-2-css.html. 

But in this example, same flag is getting displayed  for multiple countries.

<img width="1163" alt="Screenshot 2020-06-08 at 6 16 42 PM" src="https://user-images.githubusercontent.com/7972024/84032343-cd317780-a9b4-11ea-9219-fc356e26197d.png">

**Comment by bl00mber** [comment] 2020-06-08 17:07
duplicate of #182

**Closed by bl00mber** 2020-06-08 17:07 UTC
