### ISSUE TITLE
searchNotFound is not defined

### ISSUE THREAD

**Issue by mjapadilla** [bl00mber/react-phone-input-2#217] opened 2020-04-19 13:24 UTC
![image](https://user-images.githubusercontent.com/56869280/79688904-063a4f00-8284-11ea-83c9-0b73b52d9c93.png)

Page getting crush when searching country not existed on country dropdown

**Comment by bl00mber** [comment] 2020-04-19 13:42
Duplicate of #213

**Closed by bl00mber** 2020-04-19 13:42 UTC
