### ISSUE TITLE
React 18 issue

### ISSUE THREAD

**Issue by hsnlbnan** [bl00mber/react-phone-input-2#545] opened 2022-06-17 12:43 UTC
I need to update React to 18 but react-phone-input-2 doesn't support. How can i prevent this?

[2022-06-16 11:47:55] npm ERR! While resolving: react-phone-input-2@2.15.0
[2022-06-16 11:47:55] npm ERR!   react@"^18.1.0" from the root project
[2022-06-16 11:47:55] npm ERR! peer react@"^16.12.0 || ^17.0.0" from react-phone-input-2@2.15.0

**Comment by cricog** [comment] 2022-06-20 12:29
I think this issue is a duplicate of  https://github.com/bl00mber/react-phone-input-2/issues/520.
There is a PR to be tested: https://github.com/bl00mber/react-phone-input-2/pull/525.

Meanwhile, you can force using current react-phone-input-2 version, with React 18, using the `--legacy-peer-deps` npm flag.

**Closed** 2022-07-01 18:42 UTC

**Comment by sleekLancelot** [comment] 2023-06-05 02:28
The PR #525 was closed though not merged, and this project still uses react 17. Would this still be looked into?
