### ISSUE TITLE
How can i change Localization? - no way to do it!

### ISSUE THREAD

**Issue by Manimall** [bl00mber/react-phone-input-2#252] opened 2020-06-19 07:30 UTC
you add localization support - that's great - but, there is no method to change it....

in this method - 
``
UNSAFE_componentWillReceiveProps(nextProps)
``
you should add localization update

**Comment by bl00mber** [comment] 2020-06-19 08:05
duplicate of #241

**Closed by bl00mber** 2020-06-19 08:05 UTC
