### ISSUE TITLE
keep country code inside of dropdown?

### ISSUE THREAD

**Issue by znwhite** [bl00mber/react-phone-input-2#336] opened 2020-10-21 16:49 UTC
Is there any way to keep the country code inside the dropdown once it is selected?

I would like to be able to select a new country and then have the number stay inside the dropdown (I don't want the country code to be editable in the input itself). If I have to write custom JS to re-insert the country code at the beginning upon submission that is fine.

Thanks!

**Comment by znwhite** [comment] 2020-10-21 18:04
Another way of phrasing this question is- can I disable the country dial code from appearing/being editable inside of the input field?

**Comment by bl00mber** [comment] 2020-11-06 05:15
Yes, there it is. Please read the readme.md for clarification. I'm closing this since it is not a bug description.

**Closed by bl00mber** 2020-11-06 05:15 UTC

**Comment by anoop0567** [comment] 2023-04-24 11:13
@znwhite have you found any solution for this?
