### ISSUE TITLE
self is not defined

### ISSUE THREAD

**Issue by jwalton** [bl00mber/react-phone-input-2#23] opened 2018-06-08 20:33 UTC
Gave this a try, but I'm running into:

```
  err: ReferenceError: self is not defined
      at /Users/jwalton/benbria/loop-arusha-tnt/node_modules/react-phone-input-2/dist/index.js:9:603
      at /Users/jwalton/benbria/loop-arusha-tnt/node_modules/react-phone-input-2/dist/index.js:9:535
```

**Comment by bl00mber** [comment] 2018-06-09 19:27
Duplicate of #14

**Closed by bl00mber** 2018-06-09 19:27 UTC
