### ISSUE TITLE
Add inputProps

### ISSUE THREAD

**Issue by idandagan1** [bl00mber/react-phone-input-2#41] opened 2018-09-03 14:50 UTC
is it possible to add inputProps so we could send props to the input native element?

example:
```js
return (
        <input
          placeholder={this.state.placeholder}
          onChange={this.handleInput}
          ...
         {...inputProps} // like this
        />
  )
```

**Comment by bl00mber** [comment] 2018-09-07 11:57
Duplicate of #38

**Closed by bl00mber** 2018-09-07 11:57 UTC
