### ISSUE TITLE
onChange is not being called

### ISSUE THREAD

**Issue by martuanez** [bl00mber/react-phone-input-2#29] opened 2018-07-11 21:06 UTC

**Comment by martuanez** [comment] 2018-07-11 21:10
![image](https://user-images.githubusercontent.com/137611/42599358-5cf21506-8535-11e8-8f58-c5b4df9e5556.png)

**Comment by bl00mber** [comment] 2018-07-13 19:33
Error in your app, not in the component.

**Comment by ciaoben** [comment] 2018-07-17 13:58
@bl00mber it happening the same to me.

In the case of the original post, how could it be an his app error? In the snippet, it shows the function passed to the `onChange` method inline. It should always fire with the value.

Just to understand where could be the problem, thank you.

**Comment by bl00mber** [comment] 2018-07-26 11:16
JS can't call events without user interaction. If you want to trigger onChange on initial value, you can't.

**Comment by ciaoben** [comment] 2018-07-26 12:08
@bl00mber it is not about the initial value. I am talking about when I am typing in. It simply changes the input without firing the onChange callback

**Comment by eeeman1** [comment] 2018-07-26 14:22
the problem is urgent, on entering numbers does not work onChange

**Comment by eeeman1** [comment] 2018-07-27 06:10
as an example you can see this component - https://github.com/razagill/react-phone-input, everything works correctly here

**Comment by bl00mber** [comment] 2018-08-03 00:04
In my browser everything works correctly too. If you want you can freely debug and adapt to your browser.

**Comment by eeeman1** [comment] 2018-08-03 06:55
does not work for anyone, tested in the latest version of mozilla and chrome

**Comment by bl00mber** [comment] 2018-08-03 07:07
@eeeman1 stop spam this threads with meaningless messages, otherwise you'll get banned. If you want to fix this error (that is not appears in my environment), you should reveal cause of its issue. The code of onChange almost identical to react-phone-input.

**Comment by eeeman1** [comment] 2018-08-03 07:09
you did this component and it does not work for you, so you need to understand what the reason for the non-operation

**Comment by eeeman1** [comment] 2018-08-13 07:51
does not work for anyone, tested in the latest version of mozilla and chrome.
the problem remains topical

**Comment by kusumbacancy** [comment] 2018-09-12 13:55
this did not work for me too. onChange issue!

**Comment by mabeabe28** [comment] 2018-10-01 09:40
I agree, this is an issue that needs to be fixed. onChange() is not being called.

**Comment by amiklosi** [comment] 2018-10-17 15:21
How is @eeeman1 reporting a legitimate bug spamming? It seems to be an issue for others too, including myself.

**Comment by bl00mber** [comment] 2018-10-18 05:55
@amiklosi there is still no one PR suggestion or at least message about cause of the issue. I can't fix the issue which I can't reproduce. User banned there was constantly spamming with messages that contained no information just like all others comments in this thread.

**Comment by amiklosi** [comment] 2018-10-18 08:16
All I can say is that if I check out 2.6.1 and build it myself it works fine. But if install it with npm and import it then onChange doesn't get called. Did you try it like that?

**Comment by amiklosi** [comment] 2018-11-05 15:08
@bl00mber I found the issue finally. It's not compatible with React 15, works fine with 16. Not sure if there's a way around it.

**Comment by Maxhou00** [comment] 2018-12-10 03:39
Actually I have the version 16.6.3 of React and the onChange is buggy.

When I type phone number the value doesn't update in the input field.
If I select a country it will change the value of my props phone but not update the input default value and then be updated with my default country.

Here is my react-phone component
```
 <ReactPhoneInput
              defaultCountry='fr'
              regions={['europe', 'america', 'asia']}
              preferredCountries={['fr', 'us', 'kr']}
              disableAreaCodes
              enableSearchField
              onChange={this.handleChangePhone}
              className="input-phone"
              placeholder="Your phone number..."
            />

```
and my handle look like this:
```
handleChangePhone(value) {
    this.setState({ phone: value});
  }
```

When I try to remove the default country attribute, the app crash and got the following error: #60 

I think you are doing a great work, and I would like to help you as much as I can, so if you need any information to fix this problem I will try to give it to you.

**Comment by ramads** [comment] 2018-12-26 08:59
the same problem in react 15.6.
I tried to put the `handleChange` in `inputExtraProps`, it's works in my case :)

```
<ReactPhoneInput
   enableSearchField={true} 
   value={values.phone}
   defaultCountry={'id'} 
   inputExtraProps={{
     name: 'phone',
     onChange: handleChange
   }}
/>
```

**Comment by adityadhawan22** [comment] 2019-01-14 06:35
Working in React 16.7 

:)

import React, { Component } from "react";
class Test extends Component {
	constrctor(props){
		super(props);
		this.state = {number: ''};
	}
	validateNumber(e){
		console.log(e);
		this.setState({number:e});
	}

	render(){
		return(
			<div>
				<ReactPhoneInput disableAreaCodes="true" value={this.state.number} onChange={(e)=>this.validateNumber(e)} defaultCountry={'in'}  />
			</div>
		)
	}
}

**Comment by avokrado** [comment] 2019-01-24 14:15
fix for react 15.4 :)
`
handleOnChange(value) {
        this.setState({
            phone: value.target.value,
        });
    }
`
` <ReactPhoneInput
          inputExtraProps={{
               name: 'phone',
               onChange: this.handleOnChange
          }}
     value={this.state.phone}
     countryCodeEditable={false}
 />`

**Comment by kwes01** [comment] 2019-01-29 16:02
> the same problem in react 15.6.
> I tried to put the `handleChange` in `inputExtraProps`, it's works in my case :)
> 
> ```
> <ReactPhoneInput
>    enableSearchField={true} 
>    value={values.phone}
>    defaultCountry={'id'} 
>    inputExtraProps={{
>      name: 'phone',
>      onChange: handleChange
>    }}
> />
> ```

it works buy, how you can get the Dial code value?

**Comment by bl00mber** [comment] 2019-04-05 14:12
Since I have added a [test](https://github.com/bl00mber/react-phone-input-2/commit/1d5d5b943dba6703ee7a690339d190929741ebdd#diff-e1718cc77d6e2584efbfdaa94e47569fR67) proved that onChange is working, I am closing this issue.
Also I moved react to peerDependencies from dependencies (that was probably the cause of this bug in your environments).

**Closed by bl00mber** 2019-04-05 14:12 UTC

**Comment by bonatoneto** [comment] 2023-06-28 22:23
Mesmo problema aqui....
