### ISSUE TITLE
Custom Components? Dropdown, Input, Flag, …

### ISSUE THREAD

**Issue by ahmedelgabri** [bl00mber/react-phone-input-2#147] opened 2019-12-05 12:15 UTC
Do you have any plans to support custom components? Like Custom Dropdown & Custom Input?

**Comment by bl00mber** [comment] 2019-12-06 04:33
Duplicate of #113
I've tried to do this, currently without success. I do not receive any funding for this, so maybe yes, maybe no, depending on complexity of it. The solution should not overcomplicate current plugin structure, have defaults (work without custom components) and be fast and lightweight. If you want, you can send a PR or suggest ways of implementation.

**Closed by bl00mber** 2019-12-06 04:33 UTC
